create table acautelamentos (
    data_acautelamento timestamp(6),
    id bigint generated by default as identity,
    matricula_armeiro varchar(255),
    matricula_gm varchar(255),
    primary key (id)
)

create table armeiros (
    email varchar(255),
    login varchar(255),
    matricula varchar(255) not null,
    nome varchar(255),
    snha varchar(255),
    telefone varchar(255),
    primary key (matricula)
)

create table devolucoes (
    data_devolucao timestamp(6),
    id bigint generated by default as identity,
    id_acautelamento bigint unique,
    matricula_armeiro varchar(255),
    matricula_gm varchar(255),
    primary key (id)
)

create table equipamentos (
    requer_devolucao boolean,
    id bigint generated by default as identity,
    nome varchar(255),
    num_serie varchar(255),
    primary key (id)
)

create table estoques (
    id bigint generated by default as identity,
    primary key (id)
)

create table guardas_municipais (
    email varchar(255),
    matricula varchar(255) not null,
    nome varchar(255),
    telefone varchar(255),
    primary key (matricula)
)

create table itens_acautelados (
    quantidade_acautelada integer,
    id bigint generated by default as identity,
    id_acautelamento bigint,
    id_equipamento bigint unique,
    primary key (id)
)

create table itens_devolvidos (
    quantidade_devolvida integer,
    devolucao_id bigint,
    id bigint generated by default as identity,
    id_acautelamento bigint,
    id_equipamento bigint unique,
    primary key (id)
)

create table itens_estoque (
    quantidade_em_estoque integer,
    id bigint generated by default as identity,
    id_equipamento bigint unique,
    id_item_estoque bigint,
    primary key (id)
)

alter table if exists acautelamentos 
    add constraint FKiv7t3t11a6kln5kqupx9yk2lo 
    foreign key (matricula_armeiro) 
    references armeiros

alter table if exists acautelamentos 
    add constraint FKqvl60nnvpqld2vndj1gx7c1a1 
    foreign key (matricula_gm) 
    references guardas_municipais

alter table if exists devolucoes 
    add constraint FKgvgj9dl0xro558mlwxx586j0b 
    foreign key (id_acautelamento) 
    references acautelamentos

alter table if exists devolucoes 
    add constraint FKbi3ohyhq6rrm6u4mei0haeq52 
    foreign key (matricula_armeiro) 
    references armeiros

alter table if exists devolucoes 
    add constraint FKitnbava2eko63x1fdv1w5xitf 
    foreign key (matricula_gm) 
    references guardas_municipais

alter table if exists itens_acautelados 
    add constraint FKo6xdcyg6lv9nfsgsyudvaxc1i 
    foreign key (id_acautelamento) 
    references acautelamentos

alter table if exists itens_acautelados 
    add constraint FK71pcbvo4x1v9hsviojo2f8mgc 
    foreign key (id_equipamento) 
    references equipamentos

alter table if exists itens_devolvidos 
    add constraint FK6qofl4ue4rp06oxb668ll7ne 
    foreign key (id_acautelamento) 
    references acautelamentos

alter table if exists itens_devolvidos 
    add constraint FKqqxcuam8tp20dut1mro1sgla 
    foreign key (devolucao_id) 
    references devolucoes

alter table if exists itens_devolvidos 
    add constraint FKq2lf141sjvm8ema7rp8jr768a 
    foreign key (id_equipamento) 
    references equipamentos

alter table if exists itens_estoque 
    add constraint FK2q3wjhuxuh5snb189wdpxbhga 
    foreign key (id_equipamento) 
    references equipamentos

alter table if exists itens_estoque 
    add constraint FKfvnki620p6w8h1wf3qc5sl5dw 
    foreign key (id_item_estoque) 
    references estoques